# Generated by Django 5.1.4 on 2026-08-04 20:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crafts', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('village', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('island', models.CharField(max_length=200)),
                ('story', wagtail.fields.RichTextField(blank=True, null=True)),
                ('story_cultural_review_flag', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed')], default='unreviewed', max_length=20)),
                ('consent_status', models.CharField(choices=[('Signed', 'Signed'), ('Not Signed', 'Not Signed')], default='Not Signed', max_length=20)),
                ('published_flag', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('years_active', models.PositiveIntegerField(blank=True, null=True)),
                ('craft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makers', to='crafts.craftpage')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Maker',
                'verbose_name_plural': 'Makers',
            },
            bases=('wagtailcore.page',),
        ),
    ]
