# Generated by Django 5.1.4 on 2026-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerpage',
            name='portrait_alt',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='makerpage',
            name='portrait_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
