# Generated by Django 5.1.4 on 2026-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0002_makerpage_portrait_alt_makerpage_portrait_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerpage',
            name='portrait_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
