# Generated by Django 5.1.4 on 2026-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='cover_image_alt',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='cover_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
