# Generated by Django 5.1.4 on 2026-09-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlepage_cover_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='standfirst',
            field=models.TextField(blank=True, help_text='Editorial dek shown between the headline and byline on the article page.', max_length=500),
        ),
    ]
