# Generated by Django 5.1.4 on 2026-08-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='about_solomon_islands_image',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='about_team_image',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='why_we_do_this_image',
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_solomon_islands_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_team_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='why_we_do_this_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
