# Generated by Django 5.1.4 on 2026-08-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_remove_sitecontent_about_solomon_islands_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='about_solomon_islands_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='about_team_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='why_we_do_this_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
