# Generated by Django 5.1.4 on 2026-08-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_change_url_to_char_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_solomon_islands_image_alt',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_team_image_alt',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='why_we_do_this_image_alt',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
