# Generated by Django 5.1.4 on 2026-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_add_page_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_solomon_islands_heading',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_solomon_islands_link_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_solomon_islands_link_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_team_heading',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_team_link_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_team_link_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_why_heading',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_why_link_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_why_link_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
