# Generated by Django 5.1.4 on 2026-09-14 00:47

from django.db import migrations, models


def hide_supporters(apps, schema_editor):
    """Turn the "Supported by" band off on the existing singleton row.

    AlterField only changes the column default for future rows; the one
    SiteContent row that already exists (created with the old default=True)
    keeps its value. Set it to False here so the band is hidden by default and
    stays off until an admin explicitly turns it on in Admin -> Supporters.
    """
    SiteContent = apps.get_model("site_content", "SiteContent")
    SiteContent.objects.update(show_supporters=False)


def noop(apps, schema_editor):
    """Reverse is a no-op: rolling back should not silently re-enable the band."""


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0011_add_show_supporters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='show_supporters',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(hide_supporters, noop),
    ]
