# Generated by Django 5.1.4 on 2026-08-04 20:37

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField()),
                ('cultural_context', wagtail.fields.RichTextField(blank=True, null=True)),
                ('cultural_context_review_flag', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed')], default='unreviewed', max_length=20)),
                ('material_category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Craft',
                'verbose_name_plural': 'Crafts',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CraftProcessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('craft', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_images', to='crafts.craftpage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
