# Generated by Django 5.1.4 on 2026-09-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo_position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
