# Generated by Django 5.1.4 on 2026-08-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='image_alts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productpage',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
