# Generated by Django 5.1.4 on 2026-08-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('general', 'General'), ('wholesale', 'Wholesale'), ('media', 'Media'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MakerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('craft', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Maker Enquiry',
                'verbose_name_plural': 'Maker Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StockistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='stockists.stockist')),
            ],
            options={
                'verbose_name': 'Stockist Request',
                'verbose_name_plural': 'Stockist Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
