# Generated by Django 5.1.4 on 2026-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='reason',
            field=models.CharField(choices=[('general', 'General'), ('wholesale', 'Wholesale'), ('custom-order', 'Custom or bulk order'), ('media', 'Media'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
