# Generated by Django 5.1.4 on 2026-09-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_add_custom_order_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerenquiry',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='makerenquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
