# Generated by Django 5.1.4 on 2026-08-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_tokens', to='stockists.stockist')),
            ],
            options={
                'verbose_name': 'Password Set Token',
            },
        ),
    ]
