# Generated by Django 5.1.4 on 2026-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockists', '0002_add_password_set_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockist',
            name='profile_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
