# Generated by Django 5.1.4 on 2026-08-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockists', '0003_add_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
