# Generated by Django 5.1.4 on 2026-08-22 13:17

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockists', '0004_add_suspended_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='stockist_email_ci_unique'),
        ),
    ]
